export const ActionTypes = {
    GET_EMPLOYEE_LIST: "GET_EMPLOYEE_LIST",
    FAILED_GET_EMPLOYEE_LIST: "FAILED_GET_EMPLOYEE_LIST",

    GET_EMPLOYEE_DETAIL: "GET_EMPLOYEE_DETAIL",
    FAILED_GET_EMPLOYEE_DETAIL: "FAILED_GET_EMPLOYEE_DETAIL",

    SORT_BY_FIRSTNAME: "SORT_BY_FIRSTNAME",
    FAILED_SORT_BY_FIRSTNAME: "FAILED_SORT_BY_FIRSTNAME",

    SORT_BY_LASTNAME: "SORT_BY_LASTNAME",
    FAILED_SORT_BY_LASTNAME: "FAILED_SORT_BY_LASTNAME",
    
    SORT_BY_STARTDATE: "SORT_BY_STARTDATE",
    FAILED_SORT_BY_STARTDATE: "FAILED_SORT_BY_STARTDATE",

    SEARCH_BY_KEYWORDS:"SEARCH_BY_KEYWORDS",
    FAILED_SEARCH_BY_KEYWORDS:"FAILED_SEARCH_BY_KEYWORDS",
}